# -*- coding: utf-8 -*-
"""Project2_CM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unwNNHE_gjT9p3l73ExCOWfbbBxXIg5D
"""

import numpy as np
import matplotlib.pyplot as plt

class UniversalKeplerSolver:
    def __init__(self, m0=1.0, m1=0.001, a=1.0, e=0.2, h=0.01):
        self.G = 4 * np.pi**2
        self.m0 = m0
        self.m1 = m1
        self.k = self.G * (m0 + m1)
        self.a = a
        self.e = e
        self.dt = h
        self.alpha = self.k / self.a

        r0_mag = a * (1 - e)
        v0_mag = np.sqrt(self.k * (1 + e) / r0_mag)

        self.r = np.array([r0_mag, 0.0, 0.0])
        self.v = np.array([0.0, v0_mag, 0.0])

        self.E0 = self.calculate_energy(self.r, self.v)
        self.L0_vec = self.calculate_angular_momentum(self.r, self.v)
        self.L0_mag = np.linalg.norm(self.L0_vec)

    def stumpff(self, z):
        if abs(z) < 1e-6:
            c = 1/2 - z/24 + z**2/720 - z**3/40320
            s = 1/6 - z/120 + z**2/5040 - z**3/362880
        else:
            if z > 0:
                sz = np.sqrt(z)
                c = (1 - np.cos(sz)) / z
                s = (sz - np.sin(sz)) / (sz**3)
            else:
                sz = np.sqrt(-z)
                c = (np.cosh(sz) - 1) / (-z)
                s = (np.sinh(sz) - sz) / ((-z)**1.5)
        return c, s

    def get_G_functions(self, s):
        z = self.alpha * s**2
        c, stump_s = self.stumpff(z)
        g0 = 1 - self.alpha * s**2 * c
        g1 = s - self.alpha * s**3 * stump_s
        g2 = s**2 * c
        g3 = s**3 * stump_s
        return g0, g1, g2, g3

    def F_val(self, s, r0, r0_dot):
        _, g1, g2, g3 = self.get_G_functions(s)
        return r0 * g1 + r0 * r0_dot * g2 + self.k * g3 - self.dt

    def solve_s(self, method='newton', tol=1e-16, max_iter=100):
        r0 = np.linalg.norm(self.r)
        r0_dot = np.dot(self.r, self.v) / r0
        s = self.dt / r0

        if method == 'newton':
            for _ in range(max_iter):
                g0, g1, g2, g3 = self.get_G_functions(s)
                f = r0 * g1 + r0 * r0_dot * g2 + self.k * g3 - self.dt
                df = r0 * g0 + r0 * r0_dot * g1 + self.k * g2
                ds = f / df
                s -= ds
                if abs(ds) < tol: break

        elif method == 'secant':
            s_prev = s * 0.9
            for _ in range(max_iter):
                f_p = self.F_val(s_prev, r0, r0_dot)
                f_c = self.F_val(s, r0, r0_dot)
                if abs(f_c - f_p) < 1e-22: break
                s_next = s - f_c * (s - s_prev) / (f_c - f_p)
                if abs(s_next - s) < tol: break
                s_prev, s = s, s_next

        elif method == 'bisection':
            low, high = 0.0, s * 5.0
            while self.F_val(low, r0, r0_dot) * self.F_val(high, r0, r0_dot) > 0:
                high *= 2.0
            for _ in range(max_iter):
                mid = (low + high) / 2
                if self.F_val(low, r0, r0_dot) * self.F_val(mid, r0, r0_dot) < 0:
                    high = mid
                else:
                    low = mid
                if abs(high - low) < tol:
                    s = mid
                    break
        return s

    def propagate(self, method='newton'):
        r0_vec = self.r.copy()
        v0_vec = self.v.copy()
        r0_mag = np.linalg.norm(r0_vec)

        s = self.solve_s(method=method)
        g0, g1, g2, g3 = self.get_G_functions(s)

        f = 1 - (self.k / r0_mag) * g2
        g = self.dt - self.k * g3

        self.r = f * r0_vec + g * v0_vec
        r_new_mag = np.linalg.norm(self.r)

        f_dot = -(self.k / (r_new_mag * r0_mag)) * g1
        g_dot = 1 - (self.k / r_new_mag) * g2

        self.v = f_dot * r0_vec + g_dot * v0_vec

    def calculate_energy(self, r, v):
        return 0.5 * self.m1 * np.dot(v, v) - (self.G * self.m0 * self.m1) / np.linalg.norm(r)

    def calculate_angular_momentum(self, r, v):
        return np.cross(r, self.m1 * v)

methods = ['newton', 'secant', 'bisection']
steps = 1000

fig, axs = plt.subplots(1, 3, figsize=(20, 6))

for m in methods:
    sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=0.2, h=0.01)
    traj, e_err, l_err = [], [], []

    for _ in range(steps):
        sim.propagate(method=m)
        traj.append(sim.r.copy())

        current_E = sim.calculate_energy(sim.r, sim.v)
        current_L = sim.calculate_angular_momentum(sim.r, sim.v)

        energy_error = abs((sim.E0 - current_E) / sim.E0)
        momentum_error = np.linalg.norm(sim.L0_vec - current_L) / sim.L0_mag

        e_err.append(energy_error)
        l_err.append(momentum_error)

    traj = np.array(traj)
    axs[0].plot(traj[:, 0], traj[:, 1], label=f'{m}')
    axs[1].semilogy(e_err, label=m)
    axs[2].semilogy(l_err, label=m)

axs[0].set_aspect('equal')
axs[0].set_title(f'Orbital Trajectory (e={sim.e}, h={sim.dt})')
axs[0].plot(0, 0, 'o', markersize=10, label='Sun', c='yellow', markeredgecolor='orange')
axs[0].set_xlabel("x (AU)")
axs[0].set_ylabel("y (AU)")
axs[0].legend(loc = 'upper right')
axs[0].grid(True, which='both', ls='--')

axs[1].set_title("Energy Conservation Error")
axs[1].set_xlabel("Time Step"); axs[1].set_ylabel("Error")
axs[1].legend(); axs[1].grid(True)

axs[2].set_title("Angular Momentum Error")
axs[2].set_xlabel("Time Step"); axs[2].set_ylabel("Error")
axs[2].legend(); axs[2].grid(True)

plt.tight_layout()
plt.show()

eccentricities = np.arange(0.1, 1.0, 0.1)

plt.figure(figsize=(10, 10))

for i, e_val in enumerate(eccentricities):
    sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=e_val, h=0.01)

    traj = []
    for _ in range(steps):
        sim.propagate(method='newton')
        traj.append(sim.r.copy())

    traj = np.array(traj)
    plt.plot(traj[:, 0], traj[:, 1], label=f'e = {e_val:.1f}')

plt.plot(0, 0, 'o', markersize=12, label='Sun', c='yellow', markeredgecolor='orange')
plt.gca().set_aspect('equal')
plt.title(f'Orbital Trajectories (h=0.01)')
plt.xlabel('x (AU)')
plt.ylabel('y (AU)')
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
plt.grid(True, which='both', ls='--', alpha=0.6)

plt.tight_layout()
plt.show()

eccentricities = [0.1, 0.5, 0.9]
methods = ['newton', 'bisection', 'secant']
steps = 1000
h_val = 0.01

results = {method: {e: {'energy': [], 'momentum': []} for e in eccentricities} for method in methods}

for m in methods:
    for e_val in eccentricities:
        sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=e_val, h=h_val)

        for _ in range(steps):
            sim.propagate(method=m)

            curr_E = sim.calculate_energy(sim.r, sim.v)
            curr_L = sim.calculate_angular_momentum(sim.r, sim.v)

            e_err = abs((sim.E0 - curr_E) / sim.E0)
            l_err = np.linalg.norm(sim.L0_vec - curr_L) / sim.L0_mag

            results[m][e_val]['energy'].append(e_err)
            results[m][e_val]['momentum'].append(l_err)

fig1, axs1 = plt.subplots(1, 3, figsize=(20, 5), sharey=True)
fig1.suptitle(f'Energy Conservation Error (h={h_val})', fontsize=16)

for i, m in enumerate(methods):
    for e_val in eccentricities:
        axs1[i].semilogy(results[m][e_val]['energy'], label=f'e={e_val:.1f}')

    axs1[i].set_title(f'Method: {m.capitalize()}')
    axs1[i].set_xlabel('Time Step')
    axs1[i].grid(True, which='both', ls='--')
    if i == 0: axs1[i].set_ylabel("Error")
    axs1[i].legend(loc='lower right', fontsize='small')

fig2, axs2 = plt.subplots(1, 3, figsize=(20, 5), sharey=True)
fig2.suptitle(f'Angular Momentum Error (h={h_val})', fontsize=16)

for i, m in enumerate(methods):
    for e_val in eccentricities:
        axs2[i].semilogy(results[m][e_val]['momentum'], label=f'e={e_val:.1f}')

    axs2[i].set_title(f'Method: {m.capitalize()}')
    axs2[i].set_xlabel('Time Step')
    axs2[i].grid(True, which='both', ls='--')
    if i == 0: axs2[i].set_ylabel("Error")
    axs2[i].legend(loc='upper right', fontsize='small')

plt.show()

eccentricities = [0.2]
methods = ['newton', 'bisection', 'secant']
steps = 1000
h_vals = [0.05, 0.01, 0.005]

results = {
    method: {
        e: {h: {'energy': [], 'momentum': []}
            for h in h_vals}
        for e in eccentricities}
    for method in methods}

for m in methods:
    for e_val in eccentricities:
        for h_val in h_vals:
            sim = UniversalKeplerSolver( m0=1.0, m1=0.001, a=1.0, e=e_val, h=h_val)

            for _ in range(steps):
                sim.propagate(method=m)
                curr_E = sim.calculate_energy(sim.r, sim.v)
                curr_L = sim.calculate_angular_momentum(sim.r, sim.v)
                e_err = abs((sim.E0 - curr_E) / sim.E0)
                l_err = np.linalg.norm(sim.L0_vec - curr_L) / sim.L0_mag
                results[m][e_val][h_val]['energy'].append(e_err)
                results[m][e_val][h_val]['momentum'].append(l_err)

fig1, axs1 = plt.subplots(1, 3, figsize=(20, 5), sharey=True)
fig1.suptitle('Energy Conservation Error (e = 0.2)', fontsize=16)

for i, m in enumerate(methods):
    for h_val in h_vals:
        axs1[i].semilogy(
            results[m][0.2][h_val]['energy'],
            label=f'h={h_val}')

    axs1[i].set_title(f'Method: {m.capitalize()}')
    axs1[i].set_xlabel('Time Step')
    axs1[i].grid(True, which='both', ls='--')

    if i == 0:
        axs1[i].set_ylabel("Error")
    axs1[i].legend(loc='lower right', fontsize='small')

fig2, axs2 = plt.subplots(1, 3, figsize=(20, 5), sharey=True)
fig2.suptitle('Angular Momentum Error (e = 0.2)', fontsize=16)

for i, m in enumerate(methods):
    for h_val in h_vals:
        axs2[i].semilogy(
            results[m][0.2][h_val]['momentum'],
            label=f'h={h_val}')

    axs2[i].set_title(f'Method: {m.capitalize()}')
    axs2[i].set_xlabel('Time Step')
    axs2[i].grid(True, which='both', ls='--')

    if i == 0:
        axs2[i].set_ylabel("Error")

    axs2[i].legend(loc='upper right', fontsize='small')

plt.show()

test_eccentricities = [0.2, 0.5, 0.9]
test_h_values = [0.05, 0.01, 0.005]
test_methods = ['newton', 'secant', 'bisection']
steps = 1000

method_tables = {m: [] for m in test_methods}

for method_name in test_methods:
    for h_val in test_h_values:
        for e_val in test_eccentricities:
            sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=e_val, h=h_val)

            energy_errors = []
            momentum_errors = []

            for _ in range(steps):
                sim.solve_s(method=method_name)
                sim.propagate(method=method_name)
                current_E = sim.calculate_energy(sim.r, sim.v)
                rel_e_error = abs((sim.E0 - current_E) / sim.E0)
                energy_errors.append(rel_e_error)
                current_L_vec = sim.calculate_angular_momentum(sim.r, sim.v)
                rel_l_error = np.linalg.norm(sim.L0_vec - current_L_vec) / sim.L0_mag
                momentum_errors.append(rel_l_error)

            method_tables[method_name].append({
                'h': h_val,
                'e': e_val,
                'max_e': np.max(energy_errors),
                'max_l': np.max(momentum_errors)})

for method in test_methods:
    print(f"{method.upper()}")
    print(f"{'h':<10} | {'e':<5} | {'Max energy error':<22} | {'Max angular momentum error':<22}")
    print("-" * 65)

    for res in method_tables[method]:
        print(f"{res['h']:<10} | {res['e']:<5} | {res['max_e']:<22.5e} | {res['max_l']:<22.5e}")
    print("\n" + "="*65)

import numpy as np
import matplotlib.pyplot as plt

class UniversalKeplerSolver:
    def __init__(self, m0=1.0, m1=0.001, a=1.0, e=0.2, h=0.01):
        self.G = 4 * np.pi**2
        self.m0 = m0
        self.m1 = m1
        self.k = self.G * (m0 + m1)
        self.e = e
        self.dt = h

        if abs(e - 1.0) < 1e-12:
            self.alpha = 0.0
            self.a = np.inf
            r0_mag = 1.0
            v0_mag = np.sqrt(2 * self.k / r0_mag)
        elif e > 1.0:
            self.a = -abs(a)
            self.alpha = self.k / self.a
            r0_mag = self.a * (1 - e)
            v0_mag = np.sqrt(self.k * (1 + e) / r0_mag)
        else:
            self.a = a
            self.alpha = self.k / self.a
            r0_mag = a * (1 - e)
            v0_mag = np.sqrt(self.k * (1 + e) / r0_mag)

        self.r = np.array([r0_mag, 0.0, 0.0])
        self.v = np.array([0.0, v0_mag, 0.0])

        self.E0 = self.calculate_energy(self.r, self.v)
        self.L0_vec = self.calculate_angular_momentum(self.r, self.v)
        self.L0_mag = np.linalg.norm(self.L0_vec)

    def stumpff(self, z):
        if abs(z) < 1e-6:
            c = 1/2 - z/24 + z**2/720 - z**3/40320
            s = 1/6 - z/120 + z**2/5040 - z**3/362880
        else:
            if z > 0:
                sz = np.sqrt(z)
                c = (1 - np.cos(sz)) / z
                s = (sz - np.sin(sz)) / (sz**3)
            else:
                sz = np.sqrt(-z)
                c = (np.cosh(sz) - 1) / (-z)
                s = (np.sinh(sz) - sz) / ((-z)**1.5)
        return c, s

    def get_G_functions(self, s):
        z = self.alpha * s**2
        c, stump_s = self.stumpff(z)
        g0 = 1 - self.alpha * s**2 * c
        g1 = s - self.alpha * s**3 * stump_s
        g2 = s**2 * c
        g3 = s**3 * stump_s
        return g0, g1, g2, g3

    def F_val(self, s, r0, r0_dot):
        _, g1, g2, g3 = self.get_G_functions(s)
        return r0 * g1 + r0 * r0_dot * g2 + self.k * g3 - self.dt

    def solve_s(self, method='newton', tol=1e-16, max_iter=100):
        r0 = np.linalg.norm(self.r)
        r0_dot = np.dot(self.r, self.v) / r0
        s = self.dt / r0

        if method == 'newton':
            for _ in range(max_iter):
                g0, g1, g2, g3 = self.get_G_functions(s)
                f = r0 * g1 + r0 * r0_dot * g2 + self.k * g3 - self.dt
                df = r0 * g0 + r0 * r0_dot * g1 + self.k * g2
                ds = f / df
                s -= ds
                if abs(ds) < tol: break
        return s

    def propagate(self, method='newton'):
        r0_vec = self.r.copy()
        v0_vec = self.v.copy()
        r0_mag = np.linalg.norm(r0_vec)

        s = self.solve_s(method=method)
        g0, g1, g2, g3 = self.get_G_functions(s)

        f = 1 - (self.k / r0_mag) * g2
        g = self.dt - self.k * g3

        self.r = f * r0_vec + g * v0_vec
        r_new_mag = np.linalg.norm(self.r)

        f_dot = -(self.k / (r_new_mag * r0_mag)) * g1
        g_dot = 1 - (self.k / r_new_mag) * g2

        self.v = f_dot * r0_vec + g_dot * v0_vec

    def calculate_energy(self, r, v):
        return 0.5 * self.m1 * np.dot(v, v) - (self.G * self.m0 * self.m1) / np.linalg.norm(r)

    def calculate_angular_momentum(self, r, v):
        return np.cross(r, self.m1 * v)

eccentricities = [0.2, 0.9, 1.0, 1.2, 1.5, 2.0, 2.2, 2.5]
steps = 10000

plt.figure(figsize=(7, 7))

for e_val in eccentricities:
    sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=e_val, h=0.01)

    traj = []
    for _ in range(steps):
        sim.propagate(method='newton')
        traj.append(sim.r.copy())

    traj = np.array(traj)
    plt.plot(traj[:, 0], traj[:, 1], label=f'e = {e_val}')

plt.plot(0, 0, 'o', markersize=12, label='Sun', c='yellow', markeredgecolor='orange')
plt.title('Universal Orbital Trajectories')
plt.xlabel('x (AU)')
plt.ylabel('y (AU)')
plt.legend(loc='upper right')
plt.grid(True, which='both', ls='--', alpha=0.6)
plt.xlim(-5, 5)
plt.ylim(-5, 5)

plt.tight_layout()
plt.show()

if __name__ == "__main__":
    eccentricities = [0.2, 1.0, 1.2, 1.5, 2.0, 2.2, 2.5]
    steps = 10000

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    for e_val in eccentricities:
        sim = UniversalKeplerSolver(m0=1.0, m1=0.001, a=1.0, e=e_val, h=0.01)

        e_err = []
        l_err = []

        for _ in range(steps):
            sim.propagate(method='newton')

            curr_E = sim.calculate_energy(sim.r, sim.v)
            curr_L = sim.calculate_angular_momentum(sim.r, sim.v)

            e_err.append(abs((sim.E0 - curr_E) / sim.E0))
            l_err.append(np.linalg.norm(sim.L0_vec - curr_L) / sim.L0_mag)

        ax1.semilogy(e_err, label=f'e={e_val}')
        ax2.semilogy(l_err, label=f'e={e_val}')

    ax1.set_title("Energy Conservation Error")
    ax1.set_xlabel("Time Step")
    ax1.set_ylabel("Error")
    ax1.grid(True, which="both", ls="-", alpha=0.5)
    ax1.legend(loc='upper right')

    ax2.set_title("Angular Momentum Error")
    ax2.set_xlabel("Time Step")
    ax2.set_ylabel("Error")
    ax2.grid(True, which="both", ls="-", alpha=0.5)
    ax2.legend(loc='upper left')

    plt.tight_layout()
    plt.show()