# -*- coding: utf-8 -*-
"""Project3_CM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGNBruzq2l189VIe4GNmNrFLVlf-p7Hp
"""

import numpy as np
import matplotlib.pyplot as plt

class KeplerLeapfrogProject:
    def __init__(self, e=0.2, h=0.01, periods=100, ordering='O'):
        self.e = e
        self.h = h
        self.ordering = ordering
        self.tau = 2.0 * np.pi
        self.t_max = periods * self.tau
        self.steps = int(self.t_max / h)
        self.q = np.array([1.0 - e, 0.0])
        self.p = np.array([0.0, np.sqrt((1.0 + e) / (1.0 - e))])
        self.H0 = -0.5

    def get_acc(self, q):
        denom = (q[0]**2 + q[1]**2)**(1.5)
        return -q / denom

    def compute_H(self, q, p):
        return 0.5 * (p[0]**2 + p[1]**2) - 1.0 / np.sqrt(q[0]**2 + q[1]**2)

    def compute_L(self, q, p):
        return q[0] * p[1] - q[1] * p[0]

    def compute_H2(self, q, p):
        q_dot_p = q[0]*p[0] + q[1]*p[1]
        p_sq = p[0]**2 + p[1]**2
        q_sq = q[0]**2 + q[1]**2
        return (1.0 / 24.0) * (2.0 * (1.0 / (q_sq**2)) - ((p_sq / (q_sq**(1.5))) - (3.0 * (q_dot_p**2) / (q_sq**(2.5)))))

    def step(self):
        if self.ordering == 'O':
            acc_start = self.get_acc(self.q)
            p_half = self.p + (self.h / 2.0) * acc_start
            self.q = self.q + self.h * p_half
            acc_end = self.get_acc(self.q)
            self.p = p_half + (self.h / 2.0) * acc_end
        elif self.ordering == 'O_prime':
            q_half = self.q + (self.h / 2.0) * self.p
            acc_mid = self.get_acc(q_half)
            self.p = self.p + self.h * acc_mid
            self.q = q_half + (self.h / 2.0) * self.p

    def run(self):
        H_history = np.zeros(self.steps)
        H_tilde_history = np.zeros(self.steps)
        L_history = np.zeros(self.steps)
        for i in range(self.steps):
            H_history[i] = self.compute_H(self.q, self.p)
            H2_val = self.compute_H2(self.q, self.p)
            H_tilde_history[i] = H_history[i] + (self.h**2) * H2_val
            L_history[i] = self.compute_L(self.q, self.p)
            self.step()
        return H_history, H_tilde_history, L_history

    def run_trajectory(self):
        q1_history = np.zeros(self.steps)
        q2_history = np.zeros(self.steps)
        for i in range(self.steps):
            q1_history[i] = self.q[0]
            q2_history[i] = self.q[1]
            self.step()
        return q1_history, q2_history

    def compute_A(self, q, p):
        L_z = self.compute_L(q, p)
        r = np.sqrt(q[0]**2 + q[1]**2)
        Ax = p[1] * L_z - q[0] / r
        Ay = -p[0] * L_z - q[1] / r
        return np.array([Ax, Ay])

    def run_precession(self):
        A_history = np.zeros((self.steps, 2))
        for i in range(self.steps):
            A_history[i] = self.compute_A(self.q, self.p)
            self.step()
        return A_history

h=0.01
sim_long = KeplerLeapfrogProject(e=0.2, h=0.01, periods=100, ordering="O")
H_arr, H_tilde_arr, L_arr = sim_long.run()

time_periods = (np.arange(len(H_arr)) * h) / (2.0 * np.pi)

plt.figure(figsize=(8,5))
plt.plot(time_periods, H_arr, label=r"$H$", lw=0.5)
plt.plot(time_periods, H_tilde_arr, label=r"$\tilde{H}$", lw=0.5)
plt.ticklabel_format(style='plain', axis='y', useOffset=False)
plt.title("Energy conservation")
plt.xlabel("Orbital periods")
plt.ylabel("Energy")
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

plt.figure(figsize=(7, 5))
plt.plot(time_periods, L_arr - L_arr[0], lw=0.5)
plt.title("Angular momentum conservation$")
plt.xlabel("Orbital periods")
plt.ylabel("$L(t) - L(0)$")
plt.grid(True, linestyle="--", lw=0.5)
plt.tight_layout()
plt.show()

h_values = [0.05, 0.01, 0.005, 0.001]
relative_errors = []
delta_H_over_H = []

for h_test in h_values:
    sim_acc = KeplerLeapfrogProject(e=0.2, h=h_test, periods=100, ordering='O')
    H_acc, _, _ = sim_acc.run()
    max_rel_err = np.max(np.abs((H_acc - (-0.5)) / (-0.5)))
    relative_errors.append(max_rel_err)
    p2p_err = (np.max(H_acc) - np.min(H_acc)) / np.abs(-0.5)
    delta_H_over_H.append(p2p_err)

plt.figure(figsize=(7, 5))
plt.loglog(h_values, relative_errors, ':', label=r'$\frac{H - H(0)}{H(0)}$')
plt.loglog(h_values, delta_H_over_H, '--', label=r'$\frac{\Delta H}{H}$')
ideal_slope = np.array(h_values)**2 * (relative_errors[2] / (h_values[2]**2))
plt.plot(h_values, ideal_slope, '-.', label=r'$O(h^2)$')
plt.title('Second-order accuracy')
plt.xlabel('$h$')
plt.ylabel('Relative error')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

h_comp = 0.01
sim_O = KeplerLeapfrogProject(e=0.2, h=h_comp, periods=100, ordering='O')
H_O, _, _ = sim_O.run()
sim_O_prime = KeplerLeapfrogProject(e=0.2, h=h_comp, periods=100, ordering='O_prime')
H_O_prime, _, _ = sim_O_prime.run()

plt.figure()
plt.plot(np.abs((H_O - (-0.5)) / (-0.5)), label=r'$\hat{O}$', lw=0.5)
plt.plot(np.abs((H_O_prime - (-0.5)) / (-0.5)), label=r"$\hat{O}'$", lw=0.5)
plt.yscale('log')
plt.title("Error profiles for orderings $\hat{O}$ vs $\hat{O}'$")
plt.xlabel('Integrated steps')
plt.ylabel(r'$\frac{|H - H_0|}{H_0}$')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

plt.figure()
e_fixed = 0.2
h_list = [0.05, 0.01, 0.005, 0.001]
for h_val in h_list:
    sim = KeplerLeapfrogProject(e=e_fixed, h=h_val, periods=100)
    q1, q2 = sim.run_trajectory()
    plt.plot(q1, q2, label=f'h = {h_val}', lw=0.5)
plt.plot(0, 0, 'o', label='Sun', color='yellow', markeredgecolor='orange')
plt.title(f'Trajectories with fixed $e = {e_fixed}$')
plt.xlabel('$q_1$')
plt.ylabel('$q_2$')
plt.axis('equal')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

plt.figure()
h_fixed = 0.01
e_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
for e_val in e_list:
    sim = KeplerLeapfrogProject(e=e_val, h=h_fixed, periods=10)
    q1, q2 = sim.run_trajectory()
    plt.plot(q1, q2, label=f'e = {e_val}', lw=0.8)
plt.plot(0, 0, 'o', label='Sun', color='yellow', markeredgecolor='orange')
plt.title(f'Trajectories with fixed $h = {h_fixed}$ (10 periods)')
plt.xlabel('$q_1$')
plt.ylabel('$q_2$')
plt.axis('equal')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

plt.figure()
h_fixed = 0.01
e_list = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
for e_val in e_list:
    sim = KeplerLeapfrogProject(e=e_val, h=h_fixed, periods=100)
    q1, q2 = sim.run_trajectory()
    plt.plot(q1, q2, label=f'e = {e_val}', lw=0.8)
plt.plot(0, 0, 'o', label='Sun', color='yellow', markeredgecolor='orange')
plt.title(f'Trajectories with fixed $h = {h_fixed}$ (100 periods)')
plt.xlabel('$q_1$')
plt.ylabel('$q_2$')
plt.axis('equal')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

e_verify = 0.2
h_test_list = [0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001]
measured_rates = []
theoretical_rates = []

for h_val in h_test_list:
    sim_v = KeplerLeapfrogProject(e=e_verify, h=h_val, periods=100, ordering='O')
    A_track = sim_v.run_precession()
    angles = np.unwrap(np.arctan2(A_track[:, 1], A_track[:, 0]))
    omega_measured = (angles[-1] - angles[0]) / sim_v.t_max
    measured_rates.append(omega_measured)
    omega_theoretical = - (h_val**2) * (4.0 + e_verify**2) / (16.0 * (1.0 - e_verify**2)**3)
    theoretical_rates.append(omega_theoretical)
    pct_error = abs((omega_measured - omega_theoretical) / omega_theoretical) * 100
    print(f"h = {h_val} | Simulation: {omega_measured:.8e} | Theoretical: {omega_theoretical:.8e} | Error: {pct_error:.8e}%")

plt.figure(figsize=(7, 5))
plt.loglog(h_test_list, np.abs(measured_rates), 'o', label='Simulation')
plt.loglog(h_test_list, np.abs(theoretical_rates), label=r'$\langle\omega\rangle = -h^2 \frac{4+e^2}{16(1-e^2)^3}$')
plt.title(r'Precession rate $\langle\omega\rangle$')
plt.xlabel('$h$')
plt.ylabel(r'$\langle\omega\rangle$ (rad/s)')
plt.grid(True, linestyle="--", lw=0.5)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()